export const APP_VALIDATION = {
  PASSWORD_REGEX: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d]).{8,}$/,
  PASSWORD_MIN_LENGTH: 8,
} as const;

export const APP_API_CONFIG = {
  BASE_V1: '/api/v1',
} as const;

export const APP_API_ENDPOINTS = {
  AUTH: {
    LOGIN: `${APP_API_CONFIG.BASE_V1}/auth/login`,
    REGISTER: `${APP_API_CONFIG.BASE_V1}/auth/register`,
    CHECK_EMAIL: `${APP_API_CONFIG.BASE_V1}/check-email`,
  },
  TRANSACTIONS: {
    LIST: `${APP_API_CONFIG.BASE_V1}/transactions`,
    CREATE: `${APP_API_CONFIG.BASE_V1}/transactions`,
    BY_ID: (id: string) => `${APP_API_CONFIG.BASE_V1}/transactions/${id}`,
  },
  CATEGORIES: {
    LIST: `${APP_API_CONFIG.BASE_V1}/categories`,
    CREATE: `${APP_API_CONFIG.BASE_V1}/categories`,
    BY_ID: (id: string) => `${APP_API_CONFIG.BASE_V1}/categories/${id}`,
  },
} as const;

export const APP_ERROR_MESSAGES = {
  AUTH: {
    NAME_REQUIRED: 'Name is required',
    NAME_MIN_LENGTH: 'Name must be at least 2 characters',
    EMAIL_REQUIRED: 'Email is required',
    INVALID_EMAIL_FORMAT: 'Email must be a valid email address',
    EMAIL_ALREADY_TAKEN: 'Email is already taken',
    EMAIL_AVAILABILITY_CHECK_FAILED: 'Could not verify email availability',
    PASSWORD_REQUIRED: 'Password is required',
    PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters long',
    PASSWORD_COMPLEXITY: 'Min 8 chars with uppercase, lowercase, number & special character',
    CONFIRM_PASSWORD_REQUIRED: 'Confirm Password is required',
    PASSWORD_MISMATCH: "Passwords don't match",
    PASSWORD_UPPERCASE_REQUIRED: 'Password must contain at least 1 uppercase letter',
    PASSWORD_LOWERCASE_REQUIRED: 'Password must contain at least 1 lowercase letter',
    PASSWORD_NUMBER_REQUIRED: 'Password must contain at least 1 number',
    PASSWORD_SPECIAL_REQUIRED: 'Password must contain at least 1 special character',
  },
  TRANSACTION: {
    AMOUNT_REQUIRED: 'Amount is required',
    AMOUNT_POSITIVE: 'Amount must be a positive number',
    CATEGORY_REQUIRED: 'Category is required',
    DATE_REQUIRED: 'Date is required',
    DATE_INVALID: 'Date must be a valid date',
    LOAD_FAILED: 'Could not load transactions. Please try again.',
    SAVE_FAILED: 'Could not save transaction. Please try again.',
    DELETE_FAILED: 'Could not delete transaction. Please try again.',
  },
} as const;

export const APP_TEXT = {
  AUTH: {
    LOGIN_TITLE: 'Login',
    LOGIN_HERO_TITLE_LINE_1: 'Welcome Back',
    LOGIN_HERO_TITLE_HIGHLIGHT: 'Track Smarter',
    LOGIN_HERO_SUBTITLE:
      'Sign in to continue tracking expenses, reviewing reports, and managing shared bills.',
    LOGIN_EMAIL_LABEL: 'Email',
    LOGIN_EMAIL_PLACEHOLDER: 'you@example.com',
    LOGIN_PASSWORD_LABEL: 'Password',
    LOGIN_PASSWORD_PLACEHOLDER: '••••••',
    LOGIN_SUBMIT_IDLE: 'Login',
    LOGIN_SUBMIT_LOADING: 'Logging in...',
    LOGIN_FAILED_TRY_AGAIN: 'Login failed. Please try again.',
    LOGIN_NO_ACCOUNT: 'No account?',
    LOGIN_REGISTER_LINK: 'Register',
    REGISTER_TITLE: 'Register',
    REGISTER_HERO_TITLE_LINE_1: 'Start Your Journey',
    REGISTER_HERO_TITLE_HIGHLIGHT: 'To Better Money Habits',
    REGISTER_HERO_SUBTITLE:
      'Create your account to organize spending, set categories, and split expenses with ease.',
    REGISTER_NAME_LABEL: 'Full Name',
    REGISTER_NAME_PLACEHOLDER: 'John Doe',
    REGISTER_EMAIL_LABEL: 'Email',
    REGISTER_EMAIL_PLACEHOLDER: 'you@example.com',
    REGISTER_PASSWORD_LABEL: 'Password',
    REGISTER_PASSWORD_PLACEHOLDER: '••••••',
    REGISTER_CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    REGISTER_CONFIRM_PASSWORD_PLACEHOLDER: '••••••',
    REGISTER_SUBMIT: 'Register',
    REGISTER_ALREADY_HAVE_ACCOUNT: 'Already have an account?',
    REGISTER_LOGIN_LINK: 'Login',
    BACK_TO_HOME: '← Back to Home',
  },
  DASHBOARD: {
    PAGE_TITLE: 'Your Financial Overview',
    TOTAL_BALANCE_LABEL: 'Total Balance',
    MONTHLY_INCOME_LABEL: 'Monthly Income',
    MONTHLY_EXPENSES_LABEL: 'Monthly Expenses',
    SPENDING_TREND_TITLE: 'Spending Trend',
    SPENDING_TREND_SUBTITLE: 'Last 30 days',
    RECENT_TRANSACTIONS_TITLE: 'Recent Transactions',
    BUDGET_PROGRESS_TITLE: 'Budget Progress',
    TOP_CATEGORIES_TITLE: 'Top Categories',
    ADD_TRANSACTION_BTN: '+ Add Transaction',
    NAV_DASHBOARD: 'Dashboard',
    NAV_TRANSACTIONS: 'Transactions',
    NAV_BUDGETS: 'Budgets',
    NAV_GOALS: 'Goals',
    NAV_REPORTS: 'Reports',
    NAV_ACCOUNTS: 'Accounts',
    NAV_SETTINGS: 'Settings',
    USER_UPGRADE_TITLE: 'Go Premium',
    USER_UPGRADE_DESC: 'Unlock budgets, goals & reports.',
    USER_UPGRADE_BTN: 'Upgrade Now',
    TRANSACTIONS_EMPTY: 'No transactions yet. Add your first transaction.',
    TRANSACTIONS_LOADING: 'Loading transactions...',
    TRANSACTION_AMOUNT_LABEL: 'Amount',
    TRANSACTION_CATEGORY_LABEL: 'Category',
    TRANSACTION_CATEGORY_PLACEHOLDER: 'Select a category',
    TRANSACTION_DATE_LABEL: 'Date',
    TRANSACTION_DESCRIPTION_LABEL: 'Description',
    TRANSACTION_DESCRIPTION_PLACEHOLDER: 'Optional note',
    TRANSACTION_ADD_TITLE: 'Add Transaction',
    TRANSACTION_EDIT_TITLE: 'Edit Transaction',
    TRANSACTION_SAVE: 'Save',
    TRANSACTION_SAVING: 'Saving...',
    TRANSACTION_CANCEL: 'Cancel',
    TRANSACTION_DELETE_TITLE: 'Delete Transaction',
    TRANSACTION_DELETE_CONFIRM: 'Delete',
    TRANSACTION_DELETE_PROMPT: 'Are you sure you want to delete this transaction?',
    FILTER_SEARCH_PLACEHOLDER: 'Search transactions...',
    FILTER_DATE_RANGE_LABEL: 'Date Range',
    FILTER_CATEGORY_LABEL: 'Category',
    FILTER_STATUS_LABEL: 'Status',
    FILTER_RESET_BTN: 'Reset Filters',
    FILTER_ALL_TIME: 'All Time',
    FILTER_LAST_WEEK: 'Last Week',
    FILTER_LAST_MONTH: 'Last Month',
    FILTER_LAST_YEAR: 'Last Year',
    FILTER_ALL_CATEGORIES: 'All Categories',
    FILTER_ALL_STATUS: 'All Status',
    FILTER_STATUS_COMPLETED: 'Completed',
    FILTER_STATUS_PENDING: 'Pending',
  },
} as const;