export const APP_VALIDATION = {
  PASSWORD_REGEX: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d]).{8,}$/,
  PASSWORD_MIN_LENGTH: 8,
} as const;

export const APP_API_CONFIG = {
  BASE_V1: '/api/v1',
} as const;

export const APP_API_ENDPOINTS = {
  AUTH: {
    LOGIN: `${APP_API_CONFIG.BASE_V1}/auth/login`,
    REGISTER: `${APP_API_CONFIG.BASE_V1}/auth/register`,
    CHECK_EMAIL: `${APP_API_CONFIG.BASE_V1}/check-email`,
  },
  TRANSACTIONS: {
    LIST: `${APP_API_CONFIG.BASE_V1}/transactions`,
    CREATE: `${APP_API_CONFIG.BASE_V1}/transactions`,
    BY_ID: (id: string) => `${APP_API_CONFIG.BASE_V1}/transactions/${id}`,
  },
  CATEGORIES: {
    LIST: `${APP_API_CONFIG.BASE_V1}/categories`,
    CREATE: `${APP_API_CONFIG.BASE_V1}/categories`,
    BY_ID: (id: string) => `${APP_API_CONFIG.BASE_V1}/categories/${id}`,
  },
  BUDGETS: {
    LIST: `${APP_API_CONFIG.BASE_V1}/budgets`,
    CREATE: `${APP_API_CONFIG.BASE_V1}/budgets`,
    BY_ID: (id: string) => `${APP_API_CONFIG.BASE_V1}/budgets/${id}`,
  },
  GOALS: {
    LIST: `${APP_API_CONFIG.BASE_V1}/goals`,
    CREATE: `${APP_API_CONFIG.BASE_V1}/goals`,
    BY_ID: (id: string) => `${APP_API_CONFIG.BASE_V1}/goals/${id}`,
  },
  ACCOUNTS: {
    LIST: `${APP_API_CONFIG.BASE_V1}/accounts`,
    CREATE: `${APP_API_CONFIG.BASE_V1}/accounts`,
    BY_ID: (id: string) => `${APP_API_CONFIG.BASE_V1}/accounts/${id}`,
  },
  SETTINGS: {
    GET: `${APP_API_CONFIG.BASE_V1}/settings`,
    UPDATE: `${APP_API_CONFIG.BASE_V1}/settings`,
  },
} as const;

export const APP_ERROR_MESSAGES = {
  AUTH: {
    NAME_REQUIRED: 'Name is required',
    NAME_MIN_LENGTH: 'Name must be at least 2 characters',
    EMAIL_REQUIRED: 'Email is required',
    INVALID_EMAIL_FORMAT: 'Email must be a valid email address',
    EMAIL_ALREADY_TAKEN: 'Email is already taken',
    EMAIL_AVAILABILITY_CHECK_FAILED: 'Could not verify email availability',
    PASSWORD_REQUIRED: 'Password is required',
    PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters long',
    PASSWORD_COMPLEXITY: 'Min 8 chars with uppercase, lowercase, number & special character',
    CONFIRM_PASSWORD_REQUIRED: 'Confirm Password is required',
    PASSWORD_MISMATCH: "Passwords don't match",
    PASSWORD_UPPERCASE_REQUIRED: 'Password must contain at least 1 uppercase letter',
    PASSWORD_LOWERCASE_REQUIRED: 'Password must contain at least 1 lowercase letter',
    PASSWORD_NUMBER_REQUIRED: 'Password must contain at least 1 number',
    PASSWORD_SPECIAL_REQUIRED: 'Password must contain at least 1 special character',
  },
  TRANSACTION: {
    AMOUNT_REQUIRED: 'Amount is required',
    AMOUNT_POSITIVE: 'Amount must be a positive number',
    CATEGORY_REQUIRED: 'Category is required',
    DATE_REQUIRED: 'Date is required',
    DATE_INVALID: 'Date must be a valid date',
    LOAD_FAILED: 'Could not load transactions. Please try again.',
    SAVE_FAILED: 'Could not save transaction. Please try again.',
    DELETE_FAILED: 'Could not delete transaction. Please try again.',
  },
  BUDGET: {
    CATEGORY_REQUIRED: 'Budget category is required',
    LIMIT_REQUIRED: 'Budget limit is required',
    LIMIT_POSITIVE: 'Budget limit must be greater than 0',
    PERIOD_REQUIRED: 'Budget period is required',
    LOAD_FAILED: 'Could not load budgets. Please try again.',
    SAVE_FAILED: 'Could not save budget. Please try again.',
    DELETE_FAILED: 'Could not delete budget. Please try again.',
  },
  GOAL: {
    NAME_REQUIRED: 'Goal name is required',
    TARGET_REQUIRED: 'Target amount is required',
    TARGET_POSITIVE: 'Target amount must be greater than 0',
    SAVED_REQUIRED: 'Saved amount is required',
    SAVED_NON_NEGATIVE: 'Saved amount must be 0 or greater',
    SAVED_EXCEEDS_TARGET: 'Saved amount cannot exceed the target amount',
    TARGET_DATE_REQUIRED: 'Target date is required',
    TARGET_DATE_INVALID: 'Target date must be a valid date',
    LOAD_FAILED: 'Could not load goals. Please try again.',
    SAVE_FAILED: 'Could not save goal. Please try again.',
    DELETE_FAILED: 'Could not delete goal. Please try again.',
  },
  ACCOUNT: {
    NAME_REQUIRED: 'Account name is required',
    NAME_MAX: 'Account name must be at most 100 characters',
    TYPE_REQUIRED: 'Account type is required',
    TYPE_INVALID: 'Account type must be cash, bank, or card',
    BALANCE_REQUIRED: 'Balance is required',
    BALANCE_VALID: 'Balance must be a valid number',
    LOAD_FAILED: 'Could not load accounts. Please try again.',
    SAVE_FAILED: 'Could not save account. Please try again.',
    DELETE_FAILED: 'Could not delete account. Please try again.',
  },
  SETTINGS: {
    FIRST_NAME_MAX: 'First name must be at most 80 characters',
    LAST_NAME_MAX: 'Last name must be at most 80 characters',
    LOCATION_MAX: 'Location must be at most 120 characters',
    ADDRESS_MAX: 'Address must be at most 255 characters',
    COUNTRY_MAX: 'Country must be at most 100 characters',
    LOAD_FAILED: 'Could not load settings. Please try again.',
    SAVE_FAILED: 'Could not save settings. Please try again.',
  },
} as const;

export const APP_TEXT = {
  AUTH: {
    LOGIN_TITLE: 'Login',
    LOGIN_HERO_TITLE_LINE_1: 'Welcome Back',
    LOGIN_HERO_TITLE_HIGHLIGHT: 'Track Smarter',
    LOGIN_HERO_SUBTITLE:
      'Sign in to continue tracking expenses, reviewing reports, and managing shared bills.',
    LOGIN_EMAIL_LABEL: 'Email',
    LOGIN_EMAIL_PLACEHOLDER: 'you@example.com',
    LOGIN_PASSWORD_LABEL: 'Password',
    LOGIN_PASSWORD_PLACEHOLDER: '••••••',
    LOGIN_SUBMIT_IDLE: 'Login',
    LOGIN_SUBMIT_LOADING: 'Logging in...',
    LOGIN_FAILED_TRY_AGAIN: 'Login failed. Please try again.',
    LOGIN_NO_ACCOUNT: 'No account?',
    LOGIN_REGISTER_LINK: 'Register',
    REGISTER_TITLE: 'Register',
    REGISTER_HERO_TITLE_LINE_1: 'Start Your Journey',
    REGISTER_HERO_TITLE_HIGHLIGHT: 'To Better Money Habits',
    REGISTER_HERO_SUBTITLE:
      'Create your account to organize spending, set categories, and split expenses with ease.',
    REGISTER_NAME_LABEL: 'Full Name',
    REGISTER_NAME_PLACEHOLDER: 'John Doe',
    REGISTER_EMAIL_LABEL: 'Email',
    REGISTER_EMAIL_PLACEHOLDER: 'you@example.com',
    REGISTER_PASSWORD_LABEL: 'Password',
    REGISTER_PASSWORD_PLACEHOLDER: '••••••',
    REGISTER_CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    REGISTER_CONFIRM_PASSWORD_PLACEHOLDER: '••••••',
    REGISTER_SUBMIT: 'Register',
    REGISTER_ALREADY_HAVE_ACCOUNT: 'Already have an account?',
    REGISTER_LOGIN_LINK: 'Login',
    BACK_TO_HOME: '← Back to Home',
  },
  DASHBOARD: {
    PAGE_TITLE: 'Your Financial Overview',
    TOTAL_BALANCE_LABEL: 'Total Balance',
    MONTHLY_INCOME_LABEL: 'Monthly Income',
    MONTHLY_EXPENSES_LABEL: 'Monthly Expenses',
    SPENDING_TREND_TITLE: 'Spending Trend',
    SPENDING_TREND_SUBTITLE: 'Last 30 days',
    RECENT_TRANSACTIONS_TITLE: 'Recent Transactions',
    BUDGET_PROGRESS_TITLE: 'Budget Progress',
    TOP_CATEGORIES_TITLE: 'Top Categories',
    ADD_TRANSACTION_BTN: '+ Add Transaction',
    NAV_DASHBOARD: 'Dashboard',
    NAV_TRANSACTIONS: 'Transactions',
    NAV_BUDGETS: 'Budgets',
    NAV_GOALS: 'Goals',
    NAV_REPORTS: 'Reports',
    NAV_ACCOUNTS: 'Accounts',
    NAV_SETTINGS: 'Settings',
    USER_UPGRADE_TITLE: 'Go Premium',
    USER_UPGRADE_DESC: 'Unlock budgets, goals & reports.',
    USER_UPGRADE_BTN: 'Upgrade Now',
    TRANSACTIONS_EMPTY: 'No transactions yet. Add your first transaction.',
    TRANSACTIONS_LOADING: 'Loading transactions...',
    TRANSACTION_AMOUNT_LABEL: 'Amount',
    TRANSACTION_CATEGORY_LABEL: 'Category',
    TRANSACTION_CATEGORY_PLACEHOLDER: 'Select a category',
    TRANSACTION_DATE_LABEL: 'Date',
    TRANSACTION_DESCRIPTION_LABEL: 'Description',
    TRANSACTION_DESCRIPTION_PLACEHOLDER: 'Optional note',
    TRANSACTION_ADD_TITLE: 'Add Transaction',
    TRANSACTION_EDIT_TITLE: 'Edit Transaction',
    TRANSACTION_SAVE: 'Save',
    TRANSACTION_SAVING: 'Saving...',
    TRANSACTION_CANCEL: 'Cancel',
    TRANSACTION_DELETE_TITLE: 'Delete Transaction',
    TRANSACTION_DELETE_CONFIRM: 'Delete',
    TRANSACTION_DELETE_PROMPT: 'Are you sure you want to delete this transaction?',
    FILTER_SEARCH_PLACEHOLDER: 'Search transactions...',
    FILTER_DATE_RANGE_LABEL: 'Date Range',
    FILTER_CATEGORY_LABEL: 'Category',
    FILTER_STATUS_LABEL: 'Status',
    FILTER_RESET_BTN: 'Reset Filters',
    FILTER_ALL_TIME: 'All Time',
    FILTER_LAST_WEEK: 'Last Week',
    FILTER_LAST_MONTH: 'Last Month',
    FILTER_LAST_YEAR: 'Last Year',
    FILTER_ALL_CATEGORIES: 'All Categories',
    FILTER_ALL_STATUS: 'All Status',
    FILTER_STATUS_COMPLETED: 'Completed',
    FILTER_STATUS_PENDING: 'Pending',
    BUDGETS_TITLE: 'Budgets',
    BUDGETS_SUBTITLE: 'Track monthly spending limits by category.',
    BUDGET_ADD_TITLE: 'Add Budget',
    BUDGET_EDIT_TITLE: 'Edit Budget',
    BUDGET_CATEGORY_LABEL: 'Expense Category',
    BUDGET_LIMIT_LABEL: 'Monthly Limit',
    BUDGET_PERIOD_LABEL: 'Period',
    BUDGET_PERIOD_MONTHLY: 'Monthly',
    BUDGET_EMPTY: 'No budgets yet. Add a monthly budget to start tracking.',
    BUDGET_SAVE: 'Save Budget',
    BUDGET_SAVING: 'Saving Budget...',
    BUDGET_DELETE: 'Delete',
    BUDGET_EDIT: 'Edit',
    BUDGET_ADD_BUTTON: '+ Add Budget',
    BUDGET_USAGE_LABEL: 'Used this month',
    BUDGET_REMAINING_LABEL: 'Remaining',
    GOALS_TITLE: 'Goals',
    GOALS_SUBTITLE: 'Stay focused on savings milestones and deadlines.',
    GOAL_ADD_TITLE: 'Add Goal',
    GOAL_EDIT_TITLE: 'Edit Goal',
    GOAL_NAME_LABEL: 'Goal Name',
    GOAL_NAME_PLACEHOLDER: 'Emergency Fund',
    GOAL_TARGET_LABEL: 'Target Amount',
    GOAL_SAVED_LABEL: 'Saved Amount',
    GOAL_DATE_LABEL: 'Target Date',
    GOAL_EMPTY: 'No goals yet. Add your first savings goal.',
    GOAL_SAVE: 'Save Goal',
    GOAL_SAVING: 'Saving Goal...',
    GOAL_DELETE: 'Delete',
    GOAL_EDIT: 'Edit',
    GOAL_ADD_BUTTON: '+ Add Goal',
    GOAL_PROGRESS_LABEL: 'Progress',
    GOAL_REMAINING_LABEL: 'Remaining',
    GOAL_DEADLINE_LABEL: 'Target date',
    ACCOUNTS_TITLE: 'Accounts',
    ACCOUNTS_SUBTITLE: 'Manage your cash, bank, and card accounts.',
    ACCOUNT_ADD_TITLE: 'Add Account',
    ACCOUNT_EDIT_TITLE: 'Edit Account',
    ACCOUNT_NAME_LABEL: 'Account Name',
    ACCOUNT_NAME_PLACEHOLDER: 'e.g. Main Checking',
    ACCOUNT_TYPE_LABEL: 'Account Type',
    ACCOUNT_TYPE_CASH: 'Cash',
    ACCOUNT_TYPE_BANK: 'Bank',
    ACCOUNT_TYPE_CARD: 'Card',
    ACCOUNT_BALANCE_LABEL: 'Balance',
    ACCOUNT_BALANCE_PLACEHOLDER: '0.00',
    ACCOUNT_EMPTY: 'No accounts yet. Add your first account.',
    ACCOUNT_SAVE: 'Save Account',
    ACCOUNT_SAVING: 'Saving...',
    ACCOUNT_DELETE: 'Delete',
    ACCOUNT_EDIT: 'Edit',
    ACCOUNT_ADD_BUTTON: '+ Add Account',
    SETTINGS_TITLE: 'Settings',
    SETTINGS_SUBTITLE: 'Update your profile information.',
    SETTINGS_FIRST_NAME_LABEL: 'First Name',
    SETTINGS_FIRST_NAME_PLACEHOLDER: 'Jane',
    SETTINGS_LAST_NAME_LABEL: 'Last Name',
    SETTINGS_LAST_NAME_PLACEHOLDER: 'Doe',
    SETTINGS_LOCATION_LABEL: 'Location',
    SETTINGS_LOCATION_PLACEHOLDER: 'New York, NY',
    SETTINGS_ADDRESS_LABEL: 'Address',
    SETTINGS_ADDRESS_PLACEHOLDER: '123 Main St',
    SETTINGS_COUNTRY_LABEL: 'Country',
    SETTINGS_COUNTRY_PLACEHOLDER: 'Select a country',
    SETTINGS_SAVE: 'Save Settings',
    SETTINGS_SAVING: 'Saving...',
    SETTINGS_EDIT: 'Edit Profile',
    SETTINGS_CANCEL: 'Cancel',
    SETTINGS_SAVED: 'Profile saved successfully.',
  },
} as const;