export interface Country {
  code: string;
  name: string;
}

export interface CurrencyInfo {
  code: string;
  symbol: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BR', name: 'Brazil' },
  { code: 'CA', name: 'Canada' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'EG', name: 'Egypt' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Greece' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JP', name: 'Japan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'MX', name: 'Mexico' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NO', name: 'Norway' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'ES', name: 'Spain' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TR', name: 'Turkey' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'VN', name: 'Vietnam' },
];

export const COUNTRY_CURRENCY: Record<string, CurrencyInfo> = {
  AF: { code: 'AFN', symbol: '؋' },
  AL: { code: 'ALL', symbol: 'L' },
  DZ: { code: 'DZD', symbol: 'دج' },
  AR: { code: 'ARS', symbol: '$' },
  AU: { code: 'AUD', symbol: 'A$' },
  AT: { code: 'EUR', symbol: '€' },
  BE: { code: 'EUR', symbol: '€' },
  BR: { code: 'BRL', symbol: 'R$' },
  CA: { code: 'CAD', symbol: 'CA$' },
  CL: { code: 'CLP', symbol: '$' },
  CN: { code: 'CNY', symbol: '¥' },
  CO: { code: 'COP', symbol: '$' },
  HR: { code: 'EUR', symbol: '€' },
  CZ: { code: 'CZK', symbol: 'Kč' },
  DK: { code: 'DKK', symbol: 'kr' },
  EG: { code: 'EGP', symbol: 'E£' },
  FI: { code: 'EUR', symbol: '€' },
  FR: { code: 'EUR', symbol: '€' },
  DE: { code: 'EUR', symbol: '€' },
  GH: { code: 'GHS', symbol: '₵' },
  GR: { code: 'EUR', symbol: '€' },
  HU: { code: 'HUF', symbol: 'Ft' },
  IN: { code: 'INR', symbol: '₹' },
  ID: { code: 'IDR', symbol: 'Rp' },
  IE: { code: 'EUR', symbol: '€' },
  IL: { code: 'ILS', symbol: '₪' },
  IT: { code: 'EUR', symbol: '€' },
  JP: { code: 'JPY', symbol: '¥' },
  KE: { code: 'KES', symbol: 'KSh' },
  MX: { code: 'MXN', symbol: 'MX$' },
  NL: { code: 'EUR', symbol: '€' },
  NZ: { code: 'NZD', symbol: 'NZ$' },
  NG: { code: 'NGN', symbol: '₦' },
  NO: { code: 'NOK', symbol: 'kr' },
  PK: { code: 'PKR', symbol: '₨' },
  PE: { code: 'PEN', symbol: 'S/' },
  PH: { code: 'PHP', symbol: '₱' },
  PL: { code: 'PLN', symbol: 'zł' },
  PT: { code: 'EUR', symbol: '€' },
  RO: { code: 'RON', symbol: 'lei' },
  RU: { code: 'RUB', symbol: '₽' },
  SA: { code: 'SAR', symbol: '﷼' },
  ZA: { code: 'ZAR', symbol: 'R' },
  ES: { code: 'EUR', symbol: '€' },
  SE: { code: 'SEK', symbol: 'kr' },
  CH: { code: 'CHF', symbol: 'CHF' },
  TH: { code: 'THB', symbol: '฿' },
  TR: { code: 'TRY', symbol: '₺' },
  UA: { code: 'UAH', symbol: '₴' },
  GB: { code: 'GBP', symbol: '£' },
  US: { code: 'USD', symbol: '$' },
  VN: { code: 'VND', symbol: '₫' },
};

export const DEFAULT_CURRENCY: CurrencyInfo = { code: 'USD', symbol: '$' };

export function getCurrencyForCountry(countryCode: string): CurrencyInfo {
  return COUNTRY_CURRENCY[countryCode] ?? DEFAULT_CURRENCY;
}